### ISSUE TITLE
Can't create QR code with message, but without amount

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger/tangle-utils-website#2]
If I create a qr code with an address and put something in the message field nothing changes, only if I set an amount the message will also be displayed. It should be possible to create a qr code with a message, but without an amount.

<https://github.com/iotaledger/tangle-utils-website/blob/75efe1487e7bb0facf558895c1fdf1d45b411a25/client/src/app/routes/QRCreate.tsx#L181>

**Comment by obany** [comment]
Fixed
